### ISSUE TITLE
Credits page should say that Nikhil created and moderates the Discord Server.

### ISSUE THREAD

**Issue by DG3QRT1** [For-0/vocabustudy#210]

**Comment by grimsteel** [comment]
@DG3QRT1 Thanks! For future issues, can you add them to the Vocabustudy project (click the gear in the projects thing to the right and select Vocabustudy) and also use more descriptive commit messages? Instead of leaving the default like "Update index.pug" add a more descriptive summary. Also in the extended commit description box, put something like "Fixes #210" to automatically close the bug and link the commit to it.
