### ISSUE TITLE
Allow an option for ads ( yes this is stolen from monkeytype :) )

### ISSUE THREAD

**Issue by ShreyanKhanna** [For-0/vocabustudy#239]
So... we need a way to make money so that e can buy things that we need, even though this is a nonprofit and part of the reason siddhant made vocabustudy was for no ads, we are running low on money, and donations are not enough currently. 

If we want different ways to make money without violating our code of conduct(idk what else to call it), then i can think of things but this is the best and easiest way to get the money we need.

**Comment by grimsteel** [comment]
obviously not!

We are also not running low on money - there are no current expenses

**Comment by DG3QRT1** [comment]
.... no

**Comment by Nikhilatvocabustudy** [comment]
This goes against everything in the code of conduct, would not get us a penny, and is just a bad idea. Just because another website (which also has millions of users, and has a monopoly over its market, which means it can afford to pull stunts like this) does it, doesn't mean we should. It would no longer be for zero it would be "for some optional ads, so we can get pennies in revenue"

**Comment by Nikhilatvocabustudy** [comment]
Also, we have positive money, we have no expenses, and like a dollar in donation money

**Comment by Nikhilatvocabustudy** [comment]
topic is locked for the reason that it is not helpful currently
